services:
  git-server:
    image: ijskegel/gitolite-cgit
    container_name: gitolite-cgit
    env_file: config.env
    volumes:
      - git:/var/lib/git/
    ports:
      - "2222:22"
      - "8080:80"
      - "9418:9418"
    tty: true
volumes:
  git:
    driver: local
    driver_opts:
      type: none
      device: /data/git
      o: bind
